name: PHPUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '8.5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gmp
          tools: composer
          coverage: xdebug

      - name: Check PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit tests
        run: composer run test